apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ofer
spec:
  containers:
  - image: redis:alpine
    name: redis-alpine
    volumeMounts:
    - mountPath: /data/redis
      name: redis-storage-ofer
  volumes:
  - name: redis-storage-ofer
    emptyDir:
      sizeLimit: 500Mi
